### ISSUE TITLE
Tweets are missing on Firefox and Edge Browser

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#101]
Tweets are not displayed on Firefox and Edge
![image](https://user-images.githubusercontent.com/13707997/157712923-b4ff3344-b1e9-410c-a734-d4a094b1c039.png)

**Comment by bumi** [comment]
this is probably your ad blocker

**Comment by bumi** [comment]
but maybe we can hide the "What People Are Saying" when the tweets are not loading because of an ad blocker (then it would not look like something is missing)

**Comment by bumi** [comment]
I don't think it's worth doing now... too complicated for what value it brings.

but then maybe we can check the `renderError` on the tweet to hide the text or use the `onLoad` to show it.  
https://github.com/andrewsuzuki/react-twitter-widgets#common-props

**Comment by secondl1ght** [comment]
Great find @bumi, @MoritzKa I just put in a PR #102 to fix this, can you try it out and see if the tweets section no longer displays for you?

**Comment by bumi** [comment]
@MoritzKa can you confirm it's an ad blocker issue?

**Comment by MoritzKa** [comment]
sorry for the hassle. It is not due to an adblocker but likely due to a VPN. 
I guess we can close this issue.
