### ISSUE TITLE
content displacement on site load or reload

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/website#108]
https://user-images.githubusercontent.com/55848322/158820565-4e900ac9-3a72-4314-88c5-ae0380451294.mp4

**Comment by pavanjoshi914** [comment]
@secondl1ght

**Comment by secondl1ght** [comment]
Yes this happens because those buttons are checking to see if you have a compatible browser before displaying, and the button changes depending on the response.

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
