### ISSUE TITLE
Rethink about landing page vertical length

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/website#109]
I think the landing page has much more vertical length than required! 
this might decrease the interest of users to read every page by going downside. resulting in decreased visits for every page present downside making content native having no interaction with most of the users.

**Comment by pavanjoshi914** [comment]
@MoritzKa

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
