### ISSUE TITLE
Improve Lighthouse stats

### ISSUE THREAD

**Issue by RajVarsani** [getAlby/website#110]
Report :
[GETALBY_LIGHTHOUSE_REPORT.pdf](https://github.com/getAlby/website/files/8309309/GETALBY_LIGHTHOUSE_REPORT.pdf)

These were the network stats for hard reload:
![image](https://user-images.githubusercontent.com/74860406/159123684-ec2cf1b3-b632-4586-8722-b94ef508851b.png)

Typical reload with caching:
![image](https://user-images.githubusercontent.com/74860406/159123075-9fdb925f-8472-48a9-bfe5-ff155d7bdb0f.png)

Even in a typical reload, the time to get the site interactive is much higher, and there are huge layout shifts. It's mainly because of a few huge files, in particular, 1 file with a size of 8.5MB ( It alone takes around 1.2 min to load, making the user experience worse )
![image](https://user-images.githubusercontent.com/74860406/159123597-75c31d6c-a2ae-463d-a0c5-2460aed2285e.png)

**Comment by bumi** [comment]
thanks for raising this. this is not acceptable and must be fixed asap. our tiny website must also be tiny in terms of KB. 
Everyone must check that images are small (I guess those images should be way below 500kb). I should have caught that in the review. 

@RajVarsani do you know if we can add a CI check for this?
