### ISSUE TITLE
Weird behavior on larger screens.

### ISSUE THREAD

**Issue by RajVarsani** [getAlby/website#111]
- ####  The navbar moves closer to the center in larger screens.
   ![image](https://user-images.githubusercontent.com/74860406/159124078-aa4402f8-d62d-4757-b50f-384768ef5099.png)

-  #### Content and images are at different ends. Center alignment would make a better user experience, I suppose.
   ![image](https://user-images.githubusercontent.com/74860406/159124139-589244c7-b334-4aa9-aea9-7a41e8a9fa56.png)

-  #### Weird tweets alignment. also feature cards can be of less width.
   ![image](https://user-images.githubusercontent.com/74860406/159124318-9b998abd-c9ed-4791-97d8-a4981b741ad9.png)

**Comment by pavanjoshi914** [comment]
no responsiveness at all 😢

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
