### ISSUE TITLE
Small detail: bitcoin capitalization

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/website#113]
This is a small detail but some areas we use bitcoin with a capital B and other areas we use it with a lowecase b. Should we choose one and stick with it? I've seen lowercase bitcoin become more adopted over time than Bitcoin.

**Comment by escapedcat** [comment]
+1 for choosing one and sticking with it.  
When decision is made this might be a "good first issue".

**Comment by VaibhavArora19** [comment]
I can take this up.

**Comment by escapedcat** [comment]
Officially it's "Bitcoin" I guess, shoudl we use that everywhere? @reneaaron @MoritzKa ?

**Comment by MoritzKa** [comment]
Let´s follow the Bitcoin Design Guide: [Adopt lower case b for bitcoin](https://github.com/BitcoinDesign/Guide/issues/635)

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
