### ISSUE TITLE
Migrate blog from Substack to Ghost

### ISSUE THREAD

**Issue by pooniajay** [getAlby/website#124]
Further to this issue (https://github.com/getAlby/website/issues/120) here is the documentation of how to migrate substack subscribers and content from substack to ghost. https://ghost.org/docs/migration/substack/

**Comment by MoritzKa** [comment]
exported and imported all drafts and published articles. If it worked you can close that issue.
We need to check the editing and blog post specific settings: tags, metadata and facebook/Twitter cards.

**Comment by secondl1ght** [comment]
Great catch @pooniajay, I am putting in a PR for this now.

**Comment by secondl1ght** [comment]
Can this be closed now?
