### ISSUE TITLE
Add cache headers

### ISSUE THREAD

**Issue by bumi** [getAlby/website#125]
How can we enable cache-control headers and cache the page on Cloudflare?

https://github.com/getAlby/website/commit/b949a29b6bd247d679502eb2f5bb4927fae59824

I had it enabled but it seems some JS files have not been found in the cached version and the Install button is not shown - the install button is done on the client.

when does remix generate the client JS? what do we need to know to enable cache-control headers with remix

**Comment by dylancom** [comment]
The client JS is generated upon building the app for production:
```sh
npm run build
```

After that it can be served:
```sh
npm start
```

There is currently an error message to the install button though. Not sure if this is related...
(ClientOnly expects a function but gets a component directly)
Should be:
`return <ClientOnly>{() => <Install style={style} />}</ClientOnly>;`

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
