### ISSUE TITLE
Implement same header from getalby.com on blog.getalby.com

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#128]
Let's have a concise online appearance with the same header on all of our online offerings i.e. on blog.getalby.com

- Information about how to customize the template on our Ghost blog:
  https://ghost.org/docs/themes/custom-settings/
- Instructions:
  https://www.mindspun.com/blog/theming-your-ghost-site/
- Theme can be down- and uploaded here:
  https://alby.ghost.io/ghost/#/settings/design/change-theme

**Comment by secondl1ght** [comment]
This is now complete.
