### ISSUE TITLE
Create Alby in the Media footer and link to blogpost

### ISSUE THREAD

**Issue by pooniajay** [getAlby/website#134]
Create a footer item 'Alby in the Media' and connect it to the blogpost - https://blog.getalby.com/alby-in-the-media/

**Comment by secondl1ght** [comment]
@MoritzKa can you give this an ACK before I do it?

**Comment by MoritzKa** [comment]
Let´s think about what are the most important items in the footer before we implement it. 
E.g. we could also add "Media" that links to our media assets.

**Comment by secondl1ght** [comment]
> Let´s think about what are the most important items in the footer before we implement it. E.g. we could also add "Media" that links to our media assets.

We actually already have a Media link, here is a screenshot so we can see everything we currently have in the footer:

![image](https://user-images.githubusercontent.com/85003930/174505196-cd7a025e-73cf-4d2f-b975-d6577577e5c6.png)
