### ISSUE TITLE
Add newsletter signup to the footer

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#137]
We are going to have several websites (e.g. the main landing page, and the blog) To make sure users have the chance to subsribe to the newsletter on every page we can add the sign-up form to the footer and remove the current sign up section completely. 

Design proposal 
![image](https://user-images.githubusercontent.com/13707997/172554337-f481e1fc-4252-4ff3-85f1-b8375af763c3.png)
[Figma file](https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=7217%3A31972)

Remark:
- I added a checkbox for explicit consent as requested by EU law.

**Comment by MoritzKa** [comment]
@dvoroneca can you have a look at it and see if it makes sense from a UI and UX perspective?

**Comment by dvoroneca** [comment]
@MoritzKa I think it is a nice touch. I've switched places for social media and email subscription form so it doesn't change spacing when the email subscription form changes its state. 

<img width="470" alt="Screenshot 2022-06-08 at 10 15 40" src="https://user-images.githubusercontent.com/35034985/172567268-27b10ea3-a4c4-46f4-8698-5c35133c01c0.png">


Also, we don't have a component with a button in the input field yet, so there is some room to think about a design of this field. 

How about we use the same radiuses in the input files as we use in the chrome installation button in the same block.
And also we can show an input field first and upon activating we can show a GDPR required checkbox.

<img width="537" alt="Screenshot 2022-06-08 at 10 21 25" src="https://user-images.githubusercontent.com/35034985/172568467-a96d4481-c1f4-4ebc-98b7-36f7e1e5df08.png">

**Comment by MoritzKa** [comment]
Thanks for creating these different states. Switching places with social media links and re-using existing components makes sense. 
One concern that I have is the low contrast of the sign up field compared to the yellow background. Does it catch the visitors attention well enough?

**Comment by dvoroneca** [comment]
I think if the user has an intention to subscribe,  he will notice the form. Adding a white field would definitely take away the attention from all the other components on the screen.

**Comment by secondl1ght** [comment]
Great work @MoritzKa @dvoroneca, I am starting to work on this now.

**Comment by pooniajay** [comment]
good work guys, just attempting to resolve the "subscription/sign-up" and "Alby Buzz/Newsletter" copy

**Comment by secondl1ght** [comment]
PR has been merged
