### ISSUE TITLE
Add alby:image metatag

### ISSUE THREAD

**Issue by bumi** [getAlby/website#140]
Add an metatag property="alby:image" with a nice, good quality Alby icon. 

Right now it uses the icon (https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/content-script/originData.ts#L605) which has a bad quality

**Comment by secondl1ght** [comment]
I just put in a PR for this - it was still showing the old image locally though, does Alby cache the images for this?

**Comment by jankoegel** [comment]
new website has a nice `alby:image` icon, i think:
https://getalby.com/assets/alby-4f3d1e28ddfebe17a3c6bbd6344dea5f32ca0cd36514fbbd8715499cbaabdeca.png
