### ISSUE TITLE
Redesign Home Page

### ISSUE THREAD

**Issue by dvoroneca** [getAlby/website#144]
As a part of the Website redesign milestone, the Home redesign should have a Clear CTA to download the extension and further exploration of options for developers and content creators.

Steps for this page:

- [ ] Content
- [ ] Hero image

![www getalby com](https://user-images.githubusercontent.com/35034985/190975603-2e8a7a09-d275-49fd-ba70-ff66d74ad90a.png)

**Comment by dvoroneca** [comment]
## [Figma File](https://www.figma.com/file/XTK29vN4SgSZXzAE242y2l/Website-redesign?node-id=279%3A4613)

![Home](https://user-images.githubusercontent.com/35034985/191593681-3e1b4975-8b58-41e1-840a-c43b2f4f9c89.png)

**Comment by MoritzKa** [comment]
can we close when you did the handover to the developer?
