### ISSUE TITLE
Fix Catamaran font loading

### ISSUE THREAD

**Issue by jankoegel** [getAlby/website#162]
+ introduced by this commit (works in development but broken in production):
  https://github.com/getAlby/website/pull/147
+ https://getalby.slack.com/archives/C02U0KBSUGY/p1665659790192089

+ potential fix: https://gist.github.com/knowler/d74f1cdfa0d80a63910b554998eec112

**Comment by harshit0verma** [comment]
Can I work on this issue ?

**Comment by jankoegel** [comment]
Sorry, already fixed here:
https://github.com/getAlby/website/pull/163

Maybe check this list for good first issues on the browser extension:
https://github.com/getAlby/lightning-browser-extension/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
