### ISSUE TITLE
Add support widget

### ISSUE THREAD

**Issue by reneaaron** [getAlby/website#170]
Add the chatwoot support widget to the website: 

# Example of how to add scripts to remix 
https://github.com/remix-run/examples/tree/main/google-analytics

# Embed code
Configuration of the widget will be done on chatwoot.

```
    <script>
      (function(d,t) {
        var BASE_URL="https://app.chatwoot.com";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        g.defer = true;
        g.async = true;
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: 'pV5xHCk6pjSNRtpdGai57NKx',
            baseUrl: BASE_URL
          })
        }
      })(document,"script");
    </script>
```

**Comment by Abhijay007** [comment]
@reneaaron can I work on this one ?

**Comment by reneaaron** [comment]
Hi @Abhijay007! 👋 Sure, I just assigned you. Let me know if you need any help or have questions!

**Comment by Abhijay007** [comment]
> Hi @Abhijay007! 👋 Sure, I just assigned you. Let me know if you need any help or have questions!

thanks @reneaaron , I will surely ping you up if I need any assistance while implementing it :)

**Comment by jankoegel** [comment]
We're soon shutting down this repo, decided against keeping Remix in our tech stack.
