### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sam-the-tutor** [getAlby/website#176]
The link for AMBOSS API in this blog is broken. The correct link should be :
https://amboss.tech/docs/apiDocs/intro?ref=blog.getalby.com
![amboss](https://user-images.githubusercontent.com/102605200/227208353-1b920930-b289-461a-8cac-95c96046d708.png)

**Comment by jankoegel** [comment]
@sam-the-tutor thanks for notifying us about this issue. Our blog is not run by this repo, I've notified our blog team to fix the link and they will take over. Closing this issue here.
