### ISSUE TITLE
text not center-aligned

### ISSUE THREAD

**Issue by Tiana01** [getAlby/website#27]
The text doesn't seem center-aligned with the number circle. This applies to all the sections that have these numbers and text. Also is the right font-size for these sections being used? seems a lot smaller than what is in the design?
<img width="1392" alt="Screenshot 2022-01-24 at 09 43 02" src="https://user-images.githubusercontent.com/40744535/150750846-b4759a27-2125-4d3b-a73d-b811410b69de.png">

**Comment by secondl1ght** [comment]
Update: It looks like someone fixed this issue.

**Comment by Tiana01** [comment]
is there a new link to view because it still looks the same on my end

**Comment by secondl1ght** [comment]
Should be updated here: https://alby-website.netlify.app/
