### ISSUE TITLE
Blurry parts of the illustration (design issue)

### ISSUE THREAD

**Issue by Tiana01** [getAlby/website#28]
Headers of the illustrations are still blurry but i believe it's because it's a png within the svg. I will fix this asap
<img width="504" alt="Screenshot 2022-01-24 at 09 43 02" src="https://user-images.githubusercontent.com/40744535/150752352-c002a0ea-f17f-42f3-9652-6645bfa1931a.png">

**Comment by Tiana01** [comment]
I've fixed this in the design, it should look better when exported again

**Comment by secondl1ght** [comment]
I can update these images, how do I export them from Figma though? Sorry I have not used Figma much.

**Comment by Tiana01** [comment]
here..please export as svg 
<img width="1160" alt="Screenshot 2022-01-24 at 16 53 17" src="https://user-images.githubusercontent.com/40744535/150817164-06d31199-284b-414e-93af-4eab35ae6491.png">

**Comment by secondl1ght** [comment]
It looks like these images are already SVGs so someone already did this, can you check and see if it looks the way you want now?

**Comment by Tiana01** [comment]
is there a new link to view because it still looks the same on my end

**Comment by secondl1ght** [comment]
https://alby-website.netlify.app/

**Comment by secondl1ght** [comment]
Still looks a bit blurry for some reason...
