### ISSUE TITLE
Mobile view - No shadow on illustrations

### ISSUE THREAD

**Issue by Tiana01** [getAlby/website#33]
All the illustrations like the one below do not have shadows and are blending into the page
![IMG_0669](https://user-images.githubusercontent.com/40744535/151148028-e621f6ac-01fe-4e5a-b595-99f8328dd63c.PNG)

**Comment by Morrism1** [comment]
@Tiana01 most of the issues are solved in this PR https://deploy-preview-38--alby-website.netlify.app/ but We have an issue on BitcoinTv illustration as seems to have a default white background that looks bad when we add a shadow on mobile.
![Screenshot 2022-01-27 185835](https://user-images.githubusercontent.com/46853433/151408130-15e53d48-bce7-47dc-a3c2-5eabc46db997.png)

**Comment by Tiana01** [comment]
not sure why that is happening, it doesn't have any extra background in the design ... is it possible to use the illustration on the web view and resize it for mobile?

> @Tiana01 most of the issues are solved in this PR https://deploy-preview-38--alby-website.netlify.app/ but We have an issue on BitcoinTv illustration as seems to have a default white background that looks bad when we add a shadow on mobile. ![Screenshot 2022-01-27 185835](https://user-images.githubusercontent.com/46853433/151408130-15e53d48-bce7-47dc-a3c2-5eabc46db997.png)

**Comment by Tiana01** [comment]
@Morrism1 can you try exporting all the illustrations on the mobile view again to SVG. I think I've figured out the issue with them

**Comment by MoritzKa** [comment]
Did we come a bit closer to a solution on this issue?

**Comment by Morrism1** [comment]
Yeah, I have seen what was the problem. Using a shadow instead of a filter with drop-shadow on svgs which was making them look different as in the mockup
