### ISSUE TITLE
Buttons need to be hooked up

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/website#43]
Currently the 'Learn more', 'Try it now' and 'Install Alby' buttons are not hooked up. Where should each of these be directed to?

**Comment by bumi** [comment]
* the Alby logo should link to `/` 
* install Alby should link to the app store entry of the current browser (similar to the "Add to ...") on the homepage. This imo should be the exact same buttin/component as on the homepage
* Try it now should link to `/` imo
* Learn more in the lightning address section should link to `/lightning-address` - this will be served from the rails application

**Comment by secondl1ght** [comment]
Ok I have added all of these except for the 'Add to...' that one still needs to be done.
