### ISSUE TITLE
Review SEO and metatags

### ISSUE THREAD

**Issue by bumi** [getAlby/website#48]
Do we have all relevant meta tags set? open graph tags, etc.?

We need to check this for all pages `/` and `/value4value`

**Comment by bumi** [comment]
nice tool for this: https://metatags.io/

@secondl1ght do you want to check this?

**Comment by secondl1ght** [comment]
On it!

**Comment by secondl1ght** [comment]
2 PR's in for this https://github.com/getAlby/getalby.com/pull/84 and #93

**Comment by secondl1ght** [comment]
Looks like we got the metatags working now, it is using the Alby head logo which I just chose randomly. Do you like how it looks or would you prefer a different image?

**Comment by bumi** [comment]
we still have some issues there: 
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fgetalby.com

FB says: 
```
Provided og:image URL, https://getalby.com/website/_assets/alby_icon_head_icon-ICVYH45J.png was not valid because it did not meet the minimum size constraint of 200px by 200px.
```

the `og:image`  and others actually should have a special size that is good for sharing.

**Comment by bumi** [comment]
it will become something like this: 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/318/157840395-8ca14a05-8fc1-4478-b1fb-6d35bf7a8016.png">

//cc @MoritzKa

**Comment by MoritzKa** [comment]
I like that the preview shows directly what you can do instead of the Alby icon only.

**Comment by secondl1ght** [comment]
If someone can provide a perfect image for sharing we can add it in.

**Comment by MoritzKa** [comment]
I can try to create one that fits. Do we know the size of the window so that it is completely visible?

**Comment by bumi** [comment]
"Recommend 1200×628"

https://metatags.io/

let's put something up quickly it can always be easily changed.

**Comment by MoritzKa** [comment]
adjusted the size and the picture (removed the send to 50) --> need to adjust the picture on getalby.com, too.
https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=6020%3A31628
Con you try this one @secondl1ght ? I can also send it to you directly if you let me know the file type (svg, png,...)

**Comment by bumi** [comment]
Inspiration from metamask: 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/318/158059393-8f076ac1-99cb-492d-87ab-d2385016658a.png">

maybe just what we have on the landing page: 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/318/158059440-f8b8a712-8624-4e2b-9040-8daab4fbe967.png">
 
I think the tag line is important - that's what people see. isn't it?

**Comment by MoritzKa** [comment]
a bit less wordy.
https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=6023%3A31905
![Group 4553](https://user-images.githubusercontent.com/13707997/158066281-e7806dbd-7369-4355-b290-5246da478eb6.png)

**Comment by secondl1ght** [comment]
> adjusted the size and the picture (removed the send to 50) --> need to adjust the picture on getalby.com, too. https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=6020%3A31628 Con you try this one @secondl1ght ? I can also send it to you directly if you let me know the file type (svg, png,...)

There is something wrong when I try to export this - can you send to me as SVG?

**Comment by secondl1ght** [comment]
New PR in with new image #105 let's see how this one looks.

**Comment by MoritzKa** [comment]
svg sent via DM on Slack

**Comment by secondl1ght** [comment]
Does opening this SVG on your desktop work for you? This is how it appears for me, seems something is broken with it?

![image](https://user-images.githubusercontent.com/85003930/158182173-88f3e5e9-5498-422d-9dbc-b1c36952118b.png)

**Comment by secondl1ght** [comment]
Seems to work even though it is broken though.. I was using PNG format before. I'll put in a PR now and someone can confirm.

**Comment by jankoegel** [comment]
meta tags look good to me now (in the Rails app), also tested with https://metatags.io & will keep monitoring. closing this issue
