### ISSUE TITLE
Black or white hero text? 

### ISSUE THREAD

**Issue by bumi** [getAlby/website#49]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/318/152247818-003b832e-5fc2-4e2c-a48a-5bdd45a5fa56.png">
vs.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/318/152247863-0bfef574-70e7-41ef-b586-a812b06c9e01.png">

**Comment by secondl1ght** [comment]
My vote is for black

**Comment by Morrism1** [comment]
I went black. You can check it out and tell me!
