### ISSUE TITLE
Remove duplicate logo.svg and twitter.svg

### ISSUE THREAD

**Issue by bumi** [getAlby/website#51]
We have images with the same name but lower/uppercase. 
All files must be lower case!

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'public/images/Logo.svg'
  'public/images/logo.svg'
  'public/images/Twitter.svg'
  'public/images/twitter.svg'

**Comment by secondl1ght** [comment]
It doesn't look like logo.svg was being used so I deleted it and renamed Logo.svg to logo.svg.

For Twitter.svg I renamed it to twitter-logo.svg.

For each of these I also updated the import filepaths after changing the names.

I think we should be good now!
