### ISSUE TITLE
Check if the user has installed Alby and show something nice and not the install button

### ISSUE THREAD

**Issue by bumi** [getAlby/website#62]
### Ideas

* add an similar "do it" error pointing to the extension where people can send tips

**Comment by bumi** [comment]
@Tiana01 do you maybe have ideas what we could show and offer users who already have the extension installed? 
I think this would be really nice and also shows how websites could react if Alby is installed. 
@secondl1ght what do you think? maybe you could help with the brainstorming and then dev?

**Comment by bumi** [comment]
not sure about an explore button... but my thought was IF a user already has Alby installed, we do not need to show the install button, we then can show something different (not sure exactly what, that's a question).
<img width="761" alt="image" src="https://user-images.githubusercontent.com/318/153588137-6b74bc1b-3871-4b66-abbc-e863c399d706.png">

**Comment by Tiana01** [comment]
to this, I guess I could ask if it really matters if the install button remains there even though it is installed already?

Like how we have download buttons on websites where you've already downloaded the software etc

this may not be a perfect example but here even after the extension in installed, it still see this
<img width="1126" alt="Screenshot 2022-02-11 at 13 34 46" src="https://user-images.githubusercontent.com/40744535/153592506-d383ae91-7e15-47e0-8c45-bc79710ea734.png">

but if we need to, I guess we could remove the button totally and leave just the login button?

**Comment by bumi** [comment]
I don't know. was just an idea and I thought it could be a nice detail. 
but sure no idea if it matters :)

**Comment by secondl1ght** [comment]
'Thanks for using Alby!'

**Comment by rottingcleaner** [comment]
"Guides" with a link to https://guides.getalby.com/overall-guide/
Next helpful stop for Alby users.
![Screenshot 2022-10-09 at 14 43 42 1 (1)](https://user-images.githubusercontent.com/114179325/194757563-8efc8a2d-4d6f-4df8-8c89-25e6f2c6c11e.png)

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
