### ISSUE TITLE
Shift "Add to Chrome" button

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#68]
The "Add to Chrome button" overlaps with a graphical element. Can we switch it a bit to the left or bring it to the front, so that the part of the graphical element on the button is not visible anymore?
![image](https://user-images.githubusercontent.com/13707997/153172729-e2b54d56-897a-49e6-959c-67e3ab48a25d.png)

**Comment by secondl1ght** [comment]
I suggested removing this button in issue #63, can you have a look at my screenshots and let me know what you think?

**Comment by secondl1ght** [comment]
Oh nevermind, ignore my previous comment. I thought this was on the main landing page but this is value4value, I can update this button now.

**Comment by secondl1ght** [comment]
I moved it to the left, pushing changes now.

![image](https://user-images.githubusercontent.com/85003930/153242769-eb35d2d6-7878-460b-82fa-60f5b045f69d.png)
