### ISSUE TITLE
Align screenshot sizes

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#69]
The Screenshot of the BitcoinTV section is smaller than other screenshots. 
Can we increase the size of the BitcoinTV screenshot?
![image](https://user-images.githubusercontent.com/13707997/153174527-67d999f1-4445-4a90-a1f0-4ec986453b4c.png)

**Comment by secondl1ght** [comment]
While we are fixing this do we want to make that screenshot in light mode? Currently it is the only one in dark mode.

**Comment by secondl1ght** [comment]
I need Tiana or someone to send a new SVG for this image - it is currently much smaller than the other ones which is why it looks strange. All of them should be the same dimensions actually, even the others are slightly different.

**Comment by MoritzKa** [comment]
![Frame 9894](https://user-images.githubusercontent.com/13707997/154832243-38ac53d2-9e5a-4774-960c-591e2927edde.svg)
sent on Slack, too.

**Comment by secondl1ght** [comment]
Perfect thanks @MoritzKa!

One more thing - can you also send the mobile version of the SVG to match the others as well? That file also looks incorrect, there are 2 SVGs for each image size.

**Comment by secondl1ght** [comment]
Fixed with latest commit
