### ISSUE TITLE
Review Typos

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#70]
Twtter --> Twitter
![image](https://user-images.githubusercontent.com/13707997/153185057-b3a7302a-c208-4cf3-b8a7-89bf09176a40.png)

youre.blog --> your.blog
![image](https://user-images.githubusercontent.com/13707997/153185131-78635aaf-6a96-4cbe-98a3-efb861657401.png)

**Comment by secondl1ght** [comment]
Looks like @bumi fixed these so closing now.
