### ISSUE TITLE
Update styling for home page

### ISSUE THREAD

**Issue by RajVarsani** [getAlby/website#75]
On the current site, content gets farther away for larger screens, making UI a bit uncomfortable and confusing for users.

![image](https://user-images.githubusercontent.com/74860406/154485933-57534ae1-c044-4f77-83b1-a3b497a926f7.png)

It can be changed to something similar to this.

![image](https://user-images.githubusercontent.com/74860406/154486423-7ee684be-9ae2-4c87-8d4f-bf11074f69cf.png)

**Comment by bumi** [comment]
should we "zoom" with such big screens? having another response breakpoint and increase the font size for such screens?

**Comment by bumi** [comment]
//cc @Tiana01

**Comment by Tiana01** [comment]
> I wouldn't suggest increasing font sizes, The current site already has a larger font size than most of the sites; In fact, I would suggest decreasing font size for smaller screens.
> 
> In a typical laptop screen of 15.6 inches, some content is not visible in the viewport, as shown in the screenshot below. ![image](https://user-images.githubusercontent.com/74860406/155140169-39bcf417-1a20-4865-9ef7-6bb16dc2cedb.png)
> 
> To see the full content, I had to zoom out. The below screenshot is at 90% zoom. Even after zooming out, there is a spacing issue, as the top has much negative space pushing content almost at the bottom of the viewport. ![image](https://user-images.githubusercontent.com/74860406/155140928-160decf0-062a-407a-9572-070ee6d9c7d1.png)

so there's a redesign coming for this page. This design wasn't made with the current style and all I guess that's why it's that way

**Comment by Tiana01** [comment]
> ![image](https://user-images.githubusercontent.com/74860406/154486423-7ee684be-9ae2-4c87-8d4f-bf11074f69cf.png)

From a design pov I think what you suggested would work but I believe you could also bring the logo and the other menu items closer so that the logo aligns with the left side of the text and the buttons align with the right.

**Comment by RajVarsani** [comment]
Sure, Sounds good to me. I'll update that in the PR. We'll see how everything comes together.
