### ISSUE TITLE
Enhancement: "Login with Alby" button doesnt work for the current session, after first attempt of login via email and password fails

### ISSUE THREAD

**Issue by pavanjoshi914** [getAlby/website#77]
## Describe the bug
At the login page of https://getalby.com/login we are providing two ways to authenticate. 
1. ``` Login with Alby``` button
2.  manual login via email and password.

a. for the first time 
Either we can login using button or using email or password, both work fine
b. Login with email and password  with wrong credentials 
Now  try to click on  "Login with Alby" button in current session - button doesn't work

## steps to reproduce
1. visit https://getalby.com/login
2.  enter any wrong email and password and click on login
3. error msg will be shown wrong email and password.
4. Now click on "Login with Alby button"
5. see that button doesnt work for that session.

## Expected behaviour
even after login via email and password fails, login with Alby button shall work.

## Analysis
I think this happens because of , when user enters wrong email and password, route changes from ```https://getalby.com/login``` to ``` https://getalby.com/sessions```

It is not same as the behaviour shown by most of the websites

eg. 
before doing anything on the login page
route is 
``` https://circuitverse.org/users/sign_in ``` 

after entering wrong email and password
route is
```https://circuitverse.org/users/sign_in```

Now as the route is same, we can still use third party authentications such as login with github or login with google.

but in our case, our route changes and other form of logins doesnt work

**Comment by pavanjoshi914** [comment]
@secondl1ght  can you check this , if its valid I can start working on it.

**Comment by secondl1ght** [comment]
@pavanjoshi914 good catch, I can reproduce this. Yes I think if you want to start working on a fix for this you should go ahead! @bumi do you have any comments?

**Comment by bumi** [comment]
thanks for reporting this. 
Correct, it missed to initialize the lnurl-auth there. I've fixed this. can you test it again?

**Comment by pavanjoshi914** [comment]
> 

Yeah its working fine now
