### ISSUE TITLE
Unify header

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/website#79]
Currently we have a different header on every page of the website which sort of makes it feel like you are navigating to a new site every time. Should we have the same header across all pages to improve this?

**Comment by bumi** [comment]
which header are you exactly talking about? logo and navigation of the public (not logged-in) pages?

**Comment by secondl1ght** [comment]
Yes that's the one I am talking about, do you think it would be good to unify the header for all of the logged in and not logged in pages?

**Comment by bumi** [comment]
yes, that should be a reusable component. At least for all the static pages in this repo. 
the dynamic part (the rails app) works differently, so that will not be unified.

**Comment by secondl1ght** [comment]
PR in here https://github.com/getAlby/website/pull/132 and here https://github.com/getAlby/getalby.com/pull/136

**Comment by jankoegel** [comment]
We're soon shutting down this repo. Decided against keeping Remix in our tech stack.
