### ISSUE TITLE
Do not load the font from Google

### ISSUE THREAD

**Issue by bumi** [getAlby/website#83]

**Comment by secondl1ght** [comment]
So we would like to include the font in the repo instead?

**Comment by bumi** [comment]
yes, I guess so.

**Comment by secondl1ght** [comment]
I tried downloading the font and pointing to it in the public folder but I am getting a 404 message, is there something else I have to do for the app to be able to see the file?

**Comment by bumi** [comment]
I don't know. I would check how it is done with other files, check the exact paths used and google if there are special things to consider in remix.run.

**Comment by secondl1ght** [comment]
Ok I will look into this more.
