### ISSUE TITLE
Change headline and button in footer

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#99]
use the same headline: "The Bitcoin Lightning App for your Browser" and button as in the header section.
![image](https://user-images.githubusercontent.com/13707997/157701161-1c38f970-e4fc-48b1-9636-46ac89f40578.png)

**Comment by secondl1ght** [comment]
Updated

![image](https://user-images.githubusercontent.com/85003930/157708118-adf0f2a6-b27b-4691-ab86-00c041311fff.png)

**Comment by MoritzKa** [comment]
Thanks!
